apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agentmanager
  name: agentmanager
  namespace: isddc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentmanager
  strategy: {}
  template:
    metadata:
      labels:
        app: agentmanager
    spec:
      containers:
      - image: agentmanager:latest
        #imagePullPolicy: IfNotPresent 
        imagePullPolicy: Never 
        name: agentmanager-api
        env:
        - name: MONGO_URL
          value: "mongodb://isddc-mongodb:27017"
        - name: API_AUTH_MODE
          value: "None"
        - name: AUTH_URL
          value: "http://isddc-keystone:5000"
        - name: PROJECT_DOMAIN_ID
          value: "default"
        - name: USER_DOMAIN_ID
          value: "default"
        - name: PROJECT_NAME
          value: "mini-mon"
        - name: PASSWORD
          value: "password"
        - name: API_PORT
          value: "30800"
        - name: API_HOST
          value: "10.121.12.129"
---

  apiVersion: v1
  kind: Service
  metadata:
    name: agentmanager-api
    namespace: isddc
    labels:
      name: agentmanager-api
  spec:
    type: NodePort
    ports:
    - nodePort: 32666
      port: 8081
      targetPort: 8081
      protocol: TCP
    selector:
      app: agentmanager
